// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gateway/configs"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitializeApp(appCfg *configs.AppConfig) (*App, error) {
	engine := provideRouter()
	grpcServer, err := provideGRPCServer(appCfg)
	if err != nil {
		return nil, err
	}
	app := provideApp(engine, grpcServer)
	return app, nil
}

// wire.go:

type App struct {
	Router     *gin.Engine
	GRPCServer *configs.GRPCServer
}

func provideApp(router *gin.Engine, grpcServer *configs.GRPCServer) *App {
	return &App{
		Router:     router,
		GRPCServer: grpcServer,
	}
}

func provideRouter() *gin.Engine {
	r := gin.Default()
	api := r.Group("/api/v1")
	api.GET("/health", func(c *gin.Context) {
		c.JSON(200, gin.H{"status": "ok"})
	})
	return r
}

func provideGRPCServer(appCfg *configs.AppConfig) (*configs.GRPCServer, error) {
	return configs.NewGRPCServer(appCfg.GRPCPort)
}
