version: '3.8'

# =============================================================================
# BigTech Production Docker Compose
# Cloud-Native Architecture with Security and Performance Focus
# =============================================================================

# YAML anchors for DRY configuration
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

x-security: &default-security
  security_opt:
    - no-new-privileges:true
  read_only: false
  cap_drop:
    - ALL

x-resource-limits: &resource-limits
  deploy:
    resources:
      limits:
        cpus: '2.0'
        memory: 2G
      reservations:
        cpus: '0.5'
        memory: 512M
  restart: unless-stopped

services:
  # Migration service - runs once to setup database
  migration:
    image: gomicro/goose:latest
    container_name: music-player-migration
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./auth-service/migrations:/migrations:ro
    command: >
      goose
      -dir=/migrations
      postgres "postgres://postgres:postgres123@postgres:5432/music_player?sslmode=disable"
      up
    networks:
      - music-player-internal
    restart: "no"

  # Infrastructure services (giữ nguyên)
  redis-stack:
    image: redis/redis-stack:latest
    container_name: music-player-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data:Z
    environment:
      - REDIS_ARGS=--requirepass redispassword --appendonly yes --appendfsync everysec --maxmemory 1gb --maxmemory-policy allkeys-lru
      - REDIS_STACK_USERNAME=admin
      - REDIS_STACK_PASSWORD=redispassword
    networks:
      - music-player-internal
      - music-player-public
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD:-redispassword} ping | grep PONG || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  postgres:
    image: postgres:latest
    container_name: music-player-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: music_player
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    networks:
      - music-player-internal
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d music_player"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: music-player-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - music-player-internal
      - music-player-public
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: music-player-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_INIT_LIMIT: 5
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data:Z
    networks:
      - music-player-internal
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc -w 2 localhost 2181 | grep imok || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: music-player-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - kafka_data:/var/lib/kafka/data:Z
    networks:
      - music-player-internal
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:29092 --list >/dev/null 2>&1 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 8
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: music-player-kafka-ui
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      DYNAMIC_CONFIG_ENABLED: 'true'
      AUTH_TYPE: "DISABLED"
    networks:
      - music-player-internal
      - music-player-public
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # -----------------------------------------------------------------------------
  # Application Services - Environment-Driven với BigTech Standards
  # -----------------------------------------------------------------------------
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-dev}
        BUILD_TIME: "${BUILD_TIME}"
        COMMIT_SHA: "${COMMIT_SHA}"
        TARGETOS: linux
        TARGETARCH: amd64
    image: music-player/auth-service:${VERSION:-latest}
    container_name: music-player-auth
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis-stack:
        condition: service_started
      kafka:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    ports:
      - "3001:3001"
      - "50052:50052"
    env_file:
      - ./auth-service/.env
    environment:
      - SERVICE_NAME=auth-service
      - SERVICE_VERSION=${VERSION:-latest}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    networks:
      - music-player-internal
      - music-player-public
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "auth-service|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-dev}
        BUILD_TIME: "${BUILD_TIME}"
        COMMIT_SHA: "${COMMIT_SHA}"
        TARGETOS: linux
        TARGETARCH: amd64
    image: music-player/gateway:${VERSION:-latest}
    container_name: music-player-gateway
    restart: unless-stopped
    depends_on:
      - auth-service
    # 🎯 Port từ gateway/.env: APP_PORT=3000
    ports:
      - "3000:3000"      # Gateway HTTP
    env_file:
      - ./gateway/.env
    environment:
      - SERVICE_NAME=gateway
      - SERVICE_VERSION=${VERSION:-latest}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - AUTH_SERVICE_ENDPOINT=auth-service:50052
    networks:
      - music-player-internal
      - music-player-public
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "gateway|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-./data}/postgres
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-./data}/redis
  zookeeper_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-./data}/zookeeper
  kafka_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-./data}/kafka

networks:
  music-player-internal:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
  music-player-public:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1