// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"gateway/configs"
	"gateway/internal/handlers"
	"gateway/internal/middleware"
	"gateway/internal/routes"
	"gateway/internal/utils/jwt"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitializeApp(appCfg *configs.AppConfig) (*App, error) {
	grpcClients, err := provideGRPCClients(appCfg)
	if err != nil {
		return nil, err
	}
	authHandler := handlers.NewAuthHandler(grpcClients)
	twoFAHandler := handlers.NewTwoFAHandler(grpcClients)
	userHandler := handlers.NewUserHandler(grpcClients)
	jwksClient := provideJWKSClient(appCfg)
	jwtVerifier := jwt.NewJWTVerifier(jwksClient)
	authMiddleware := middleware.NewAuthMiddleware(jwtVerifier)
	engine := provideRouter(authHandler, twoFAHandler, userHandler, authMiddleware)
	app := provideApp(engine, grpcClients, authHandler, twoFAHandler, userHandler, authMiddleware)
	return app, nil
}

// wire.go:

type App struct {
	Router         *gin.Engine
	GRPCClients    *configs.GRPCClients
	AuthHandler    *handlers.AuthHandler
	TwoFAHandler   handlers.TwoFAHandler
	UserHandler    handlers.UserHandler
	AuthMiddleware *middleware.AuthMiddleware
}

func provideApp(
	router *gin.Engine,
	grpcClients *configs.GRPCClients,
	authHandler *handlers.AuthHandler,
	twoFAHandler handlers.TwoFAHandler,
	userHandler handlers.UserHandler,
	authMiddleware *middleware.AuthMiddleware,
) *App {
	return &App{
		Router:         router,
		GRPCClients:    grpcClients,
		AuthHandler:    authHandler,
		TwoFAHandler:   twoFAHandler,
		UserHandler:    userHandler,
		AuthMiddleware: authMiddleware,
	}
}

func provideRouter(
	authHandler *handlers.AuthHandler,
	twoFAHandler handlers.TwoFAHandler,
	userHandler handlers.UserHandler,
	authMiddleware *middleware.AuthMiddleware,
) *gin.Engine {
	r := gin.Default()
	routes.SetupAuthRoutes(r, authHandler, twoFAHandler, userHandler, authMiddleware)

	return r
}

func provideGRPCClients(appCfg *configs.AppConfig) (*configs.GRPCClients, error) {
	ctx := context.Background()

	return configs.NewGRPCClients(ctx, appCfg.AuthServiceAddr)
}

func provideJWKSClient(appCfg *configs.AppConfig) *jwt.JWKSClient {
	return jwt.NewJWKSClient(appCfg.AuthServiceHTTPURL)
}
