// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"notification/configs"
)

// Injectors from wire.go:

func InitializeApp(app *configs.AppConfig) (*App, error) {
	engine := provideRouter()
	mainApp := provideApp(engine)
	return mainApp, nil
}

// wire.go:

type App struct {
	Router *gin.Engine
}

func provideApp(router *gin.Engine) *App {
	return &App{
		Router: router,
	}
}

func provideRouter() *gin.Engine {
	r := gin.Default()

	return r
}
